# Generated by Django 4.2.22 on 2025-06-24 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="quizzes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participation",
                to="quiz.invitation",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quiz_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="participations", to="quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invited",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invitations", to="quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="answersubmission",
            name="participation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answer_submissions", to="quiz.participation"
            ),
        ),
        migrations.AddField(
            model_name="answersubmission",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="quiz.question"),
        ),
        migrations.AddField(
            model_name="answersubmission",
            name="selected_answer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="quiz.answer"),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="quiz.question"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quiz",
            unique_together={("title", "creator")},
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("quiz", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together={("quiz", "participant")},
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("quiz", "invited")},
        ),
        migrations.AlterUniqueTogether(
            name="answersubmission",
            unique_together={("participation", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "order")},
        ),
    ]
